version: '3.8'
services:
  ls10_net_pwa_application:
    # container_name: ls10_net_pwa-application
    build:
      context: .
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "8082:8082"
    # depends_on:
    #   - ls10_net_server_application
    # volumes:
    #    - ./../../ls10_net_pwa:/usr/src/app/ls10_net_pwa
    #    - /usr/src/app/ls10_net_pwa/node_modules